version: 2.1

orbs:
  pipeline: relaxdiego/package-pipeline@dev:alpha

workflows:
  pipeline:
    jobs:
      - pipeline/stage:
          name: build

          package-repo-provider: circleci-orb
          package-repo: relaxdiego/package-pipeline
          versioning-scheme: semver2

      # - pipeline/stage:
      #     name: dev
      #     requires:
      #       - build
      #
      #     package-repo-provider: circleci-orb
      #     package-repo: relaxdiego/package-pipeline
      #     versioning-scheme: semver2
