version: 2.1

orbs:
  pipeline: relaxdiego/package-pipeline@dev:alpha

workflows:
  pipeline:
    jobs:
      - pipeline/stage:
          name: build
          # Defined in Organization Settings > Contexts
          # Makes CIRCLE_TOKEN env var available to the build environment
          context: orb-publishing
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

          package-repo-provider: circleci-orb
          package-repo: relaxdiego/package-pipeline
          versioning-scheme: semver2

      # - pipeline/stage:
      #     name: dev
      #     requires:
      #       - build
      #
      #     package-repo-provider: circleci-orb
      #     package-repo: relaxdiego/package-pipeline
      #     versioning-scheme: semver2
