version: 2.1

#
# PIPELINE PARAMETERS
#
parameters:
  vet-the-orb:
    description: >
      This is an internal parameter. DO NOT SET THIS. It's used internally by
      this config to determine whether the vetting workflow should be executed.
      This is set to true by the pre-vetting workflow after it has packed to
      orb and pushed it to the orb registry with the version
      dev:<X.Y.Z>-<GIT-SHORT-SHA>.<PIPELINE-INSTANCE-ID>
    type: boolean
    default: false

  orb-version-to-vet:
    description: >
      DO NOT SET THIS. This is an internal parameter used by this pipeline
      to determine which version of the orb to run vet. The value for this
      parmeter will be set by the pre-vetting workflow.
    type: string
    # This version must have been already published manually in order for
    # this pipeline to work. Note that during the execution of the pre-vetting
    # workflow, this is just a placeholder (that must point to a valid version).
    # When this pipeline triggers the post-dev workflow, it will change
    # this to the correct value.
    default: "0.1"


#
# ORBS. The pipeline orb is used only in the vetting workflow.
#
orbs:
  pipeline: relaxdiego/package-pipeline@<< pipeline.parameters.orb-version-to-vet >>
  # https://circleci.com/developer/orbs/orb/circleci/orb-tools
  orb-tools: circleci/orb-tools@10.0
  # https://circleci.com/developer/orbs/orb/circleci/bats
  bats: circleci/bats@1.0
  # https://circleci.com/developer/orbs/orb/circleci/shellcheck
  shellcheck: circleci/shellcheck@2.0
  # https://circleci.com/developer/orbs/orb/circleci/circleci-cli
  circleci-cli: circleci/circleci-cli@0.1
  # https://circleci.com/developer/orbs/orb/circleci/jq
  jq: circleci/jq@2.2


#
# JOBS. These are used only in the pre-vetting workflow.
#
jobs:
  prepare-build-info:
    executor: circleci-cli/default
    steps:
      - checkout

      - run:
          name: Render dev BUILD-INFO
          command: |
             bash .circleci/pre-vetting/scripts/render-dev-build-info.sh > BUILD-INFO

             echo "BUILD-INFO contents:"
             cat BUILD-INFO

      - persist_to_workspace:
          root: .
          paths:
            - BUILD-INFO

  build-orb:
    executor: circleci-cli/default
    steps:
      - attach_workspace:
          at: ~/workspace

      - checkout

      - run:
          name: Validate orb
          command: |
            cat > orb.yml <<EOF
            # $(jq --compact . BUILD_INFO)
            EOF
            circleci orb pack src >> orb.yml
            circleci orb validate orb.yml

            head -n5 orb.yml

      - persist_to_workspace:
          root: .
          paths:
            - orb.yml

  publish-dev-orb:
    executor: circleci-cli/default
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Publish the orb
          command: |
            # if [ -z "$CIRCLE_TOKEN" ]; then
            #     echo "FATAL: CIRCLE_TOKEN is not defined! To fix this error, make sure the" \
            #          "job is given a Circle CI context that defines the CIRCLE_TOKEN env var." \
            #          "See https://circleci.com/docs/2.0/contexts/ for more information." 1>&2
            #     exit 1
            # fi
            #
            # PIPELINE_BUILD_ID=$(jq -r .build_id BUILD-INFO)
            # circleci orb publish \
            #   --skip-update-check \
            #   orb.yml \
            #   "${PIPELINE_PACKAGE_REPO}@${PIPELINE_BUILD_ID}" \
            #   --token "$CIRCLE_TOKEN"

            ls -l
            cat BUILD-INFO


#
# WORKFLOWS. Divided in to two stages. The first is a pre-vetting workflow which
#            concerned with vetting, building, and publishing a dev release orb.
#            It will then trigger the the vetting workflow which will subjet the
#            pre-release orb through various integration tests. At the end of
#            this process, the vetting workflow will wait for approval to promote
#            the orb to a production release.
workflows:
  # Prepare the orb and publish it as a dev releaseso that the vetting workflow
  # can run against the version that we create and publish here
  #
  # All jobs in this workflow MUST NOT use elements defined in the orb since
  # we cannot depend on unvetted elements in the SUT to perform our pre-vetting!
  #
  # IMPORTANT: All jobs in this workflow SHOULD not use the orb being developed!
  pre-vetting:
    unless: << pipeline.parameters.vet-the-orb >>
    jobs:
      - prepare-build-info:
          name: Prepare BUILD-INFO


      - orb-tools/lint:
          name: Lint YAML files
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*


      - shellcheck/check:
          name: Check scripts syntax
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

          dir: ./src/scripts
          exclude: SC2148


      - bats/run:
          name: Run BATS tests
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

          path: ./src/tests


      - build-orb:
          name: Build the validate the orb
          requires:
            - Prepare BUILD-INFO
            - Lint YAML files
            - Check scripts syntax
            - Run BATS tests
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*


      - approve-for-release:
          name: Wait for approval to release to production
          requires:
            - Build the validate the orb
          type: approval


      - publish-dev-orb:
          name: Publish orb as a dev pre-release
          requires:
            - Wait for approval to release to production
          context: orb-publishing
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

      #       steps:
      #         - persist_to_workspace:
      #             root: .
      #             paths:
      #               - BUILD-INFO
      #               - orb.yml
      #
      # - trigger-vetting-workflow:
      #     name: Trigger post-dev workflow
      #     context: orb-publishing
      #     requires:
      #       - Publish dev pre-release

  # This workflow is triggered by the pre-vetting workflow. By this time,
  # pipeline.parameters.pipeline will have already been set to the orb that
  # was published by the pre-vetting workflow. At this point, this workflow's
  # job is to use various elements of the orb as a way to vet its correctnes.
  # At the end of this vetting process, the orb will be promoted to a final release.
  # vetting:
  #   when: << pipeline.parameters.vet-the-orb >>
  #   jobs:
  #     - pipeline/build-and-test:
  #         name: build-and-test
  #         context: orb-publishing
  #         filters:
  #           branches:
  #             only:
  #               - main
  #               - maint/.*
  #           tags:
  #             ignore:
  #               - .*
  #
  #         package-repo: relaxdiego/package-pipeline
  #         package-repo-provider: circleci-orb
  #         package-type: circleci-orb
  #         versioning-provider: semver2
  #
      # - pipeline/validate-and-promote:
      #     name: dev
      #     requires:
      #       - build
      #
      #     package-repo-provider: circleci-orb
      #     package-repo: relaxdiego/package-pipeline
      #     versioning-scheme: semver2
