version: 2.1

# This is a dynamic configuration file
#
# IMPORTANT: The CircleCI project must enable dynamic configuration. Do this
#            via Project Settings > Advanced > Enable dynamic config
setup: true

#
# PIPELINE PARAMETERS
#
parameters:
  orb-repo:
    description: The orb repo where this orb is to be published.
    type: string
    default: relaxdiego/package-pipeline


#
# ORBS.
#
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/orb-tools
  orb-tools: circleci/orb-tools@10.0
  # https://circleci.com/developer/orbs/orb/circleci/bats
  bats: circleci/bats@1.0
  # https://circleci.com/developer/orbs/orb/circleci/shellcheck
  shellcheck: circleci/shellcheck@2.0
  # https://circleci.com/developer/orbs/orb/circleci/circleci-cli
  circleci-cli: circleci/circleci-cli@0.1
  # https://circleci.com/developer/orbs/orb/circleci/jq
  jq: circleci/jq@2.2
  # the continuation orb is required in order to use dynamic configuration
  # https://circleci.com/developer/orbs/orb/circleci/continuation
  continuation: circleci/continuation@0.1.2


jobs:
  render-build-info:
    executor: circleci-cli/default
    steps:
      - checkout

      - run:
          name: Render BUILD-INFO
          environment:
            PL_VERSIONING_SCHEME: semver2
          command: bash src/scripts/render-build-info.sh

      - persist_to_workspace:
          root: .
          paths:
            - BUILD-INFO

  build-orb:
    executor: circleci-cli/default
    steps:
      - attach_workspace:
          at: ~/workspace

      - checkout

      - run:
          name: Build orb
          environment:
            PL_ORB_SRC_PATH: src
            PL_ORB_TARGET_FILENAME: orb.yml
          command: bash src/scripts/build/orb.sh

      - persist_to_workspace:
          root: .
          paths:
            - orb.yml

  publish-orb-pre-release:
    executor: circleci-cli/default
    environment:
      PL_BUILD_INFO_PATH: ~/workspace/BUILD-INFO
      PL_ORB_IS_PRERELEASE: true
      PL_ORB_PATH: ~/workspace/orb.yml
      PL_PACKAGE_REPO: << pipeline.parameters.orb-repo >>
      PL_PACKAGE_REPO_PROVIDER: circleci-orb
    steps:
      - attach_workspace:
          at: ~/workspace

      - jq/install

      - checkout

      - run:
          name: Publish the orb
          command: |
            bash src/scripts/publish.sh

  trigger-integration-tests:
    executor: continuation/default
    environment:
      PIPELINE_ORB_REPO: << pipeline.parameters.orb-repo >>
    steps:
      - attach_workspace:
          at: ~/workspace

      - jq/install

      - checkout

      # The integration test is triggered via a dynamic config so that this
      # config (.circleci/config.yml) doesn't have to reference via the orbs
      # stanza dummy version of the orb. By using a dynamic config, we only
      # need to specify the exact version we want to test AFTER the orb has
      # been built and published.

      - run:
          name: Render the integration tests workflow
          command: |
            bash .circleci/scripts/render-integration-tests.sh > integration-tests.yml

      - continuation/continue:
          configuration_path: integration-tests.yml


workflows:
  build-orb:
    jobs:
      - render-build-info:
          name: Render BUILD-INFO

      #
      # Orb unit tests and linters
      #

      - orb-tools/lint:
          name: Lint YAML files
          filters:
            tags:
              ignore:
                - .*


      - shellcheck/check:
          name: Run ShellCheck
          filters:
            tags:
              ignore:
                - .*

          dir: ./src/scripts
          exclude: SC2148


      - bats/run:
          name: Run BATS tests
          filters:
            tags:
              ignore:
                - .*

          path: ./src/tests


      - build-orb:
          name: Build the orb
          requires:
            - Render BUILD-INFO
            - Lint YAML files
            - Run ShellCheck
            - Run BATS tests
          filters:
            branches:
            tags:
              ignore:
                - .*


      - publish-orb-pre-release:
          name: Publish orb as a dev pre-release
          requires:
            - Build the orb
          context: orb-publishing
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*


      - trigger-integration-tests:
          name: Trigger integration tests
          context: orb-publishing
          requires:
            - Publish orb as a dev pre-release
