version: 2.1

# This is a dynamic configuration file
#
# IMPORTANT: The CircleCI project must enable dynamic configuration. Do this
#            via Project Settings > Advanced > Enable dynamic config
setup: true

#
# PIPELINE PARAMETERS
#
parameters:
  orb-repo:
    description: The orb repo where this orb is to be published.
    type: string
    default: relaxdiego/package-pipeline


#
# ORBS.
#
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/orb-tools
  orb-tools: circleci/orb-tools@10.0
  # https://circleci.com/developer/orbs/orb/circleci/bats
  bats: circleci/bats@1.0
  # https://circleci.com/developer/orbs/orb/circleci/shellcheck
  shellcheck: circleci/shellcheck@2.0
  # https://circleci.com/developer/orbs/orb/circleci/circleci-cli
  circleci-cli: circleci/circleci-cli@0.1
  # https://circleci.com/developer/orbs/orb/circleci/jq
  jq: circleci/jq@2.2
  # the continuation orb is required in order to use dynamic configuration
  # https://circleci.com/developer/orbs/orb/circleci/continuation
  continuation: circleci/continuation@0.1.2


jobs:
  prepare-build-info:
    executor: circleci-cli/default
    steps:
      - checkout

      - run:
          name: Render dev BUILD-INFO
          command: |
             bash .circleci/scripts/render-build-info.sh > BUILD-INFO

             echo "BUILD-INFO contents:"
             cat BUILD-INFO

      - persist_to_workspace:
          root: .
          paths:
            - BUILD-INFO

  build-dev-orb:
    executor: circleci-cli/default
    steps:
      - attach_workspace:
          at: ~/workspace

      - checkout

      - run:
          name: Build orb
          command: |
            # Prepend BUILD-INFO contents as a single-line comment
            echo "# pipeline:build-info $(jq -c . ~/workspace/BUILD-INFO)" > orb.yml
            circleci orb pack src >> orb.yml
            head -n5 orb.yml

      - run:
          name: Validate orb
          command: |
            circleci orb validate orb.yml

      - persist_to_workspace:
          root: .
          paths:
            - orb.yml

  publish-dev-orb:
    executor: circleci-cli/default
    environment:
      PIPELINE_PACKAGE_REPO: << pipeline.parameters.orb-repo >>
    steps:
      - attach_workspace:
          at: ~/workspace

      - jq/install

      - checkout

      - run:
          name: Publish the dev orb
          command: |
            bash .circleci/scripts/publish.sh

  trigger-integration-tests:
    executor: continuation/default
    environment:
      PIPELINE_ORB_REPO: << pipeline.parameters.orb-repo >>
    steps:
      - attach_workspace:
          at: ~/workspace

      - jq/install

      - checkout

      # The integration test is triggered via a dynamic config so that this
      # config (.circleci/config.yml) doesn't have to reference via the orbs
      # stanza dummy version of the orb. By using a dynamic config, we only
      # need to specify the exact version we want to test AFTER the orb has
      # been built and published.

      - run:
          name: Render the integration tests workflow
          command: |
            bash .circleci/scripts/render-integration-tests.sh > integration-tests.yml

      - continuation/continue:
          configuration_path: integration-tests.yml


workflows:
  build-orb:
    jobs:
      - prepare-build-info:
          name: Prepare BUILD-INFO

      #
      # Orb unit tests and linters
      #

      - orb-tools/lint:
          name: Lint YAML files
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*


      - shellcheck/check:
          name: Check scripts syntax
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

          dir: ./src/scripts
          exclude: SC2148


      - bats/run:
          name: Run BATS tests
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

          path: ./src/tests


      - build-dev-orb:
          name: Build the validated orb
          requires:
            - Prepare BUILD-INFO
            - Lint YAML files
            - Check scripts syntax
            - Run BATS tests
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*


      - publish-dev-orb:
          name: Publish orb as a dev pre-release
          requires:
            - Build the validated orb
          context: orb-publishing
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*


      - trigger-integration-tests:
          name: Trigger integration tests
          context: orb-publishing
          requires:
            - Publish orb as a dev pre-release
