#
# This template is a dynamic configuration that the main .circleci/config.yml
# renders and then triggers. For more information on dynamic configurations,
# see https://circleci.com/docs/2.0/dynamic-config/
#
# The purpose of this config is to allow our main workflow in .circleci/config.yml
# to test each of the jobs that we define in src/jobs. In effect, this is an
# integration test for the orb that this pipeline is building.
#
# Yeah, we're using a Circle CI config to test an orb which is essentially
# a packaged, parameterized Circle CI config. :-)
#
version: 2.1

orbs:
  pipeline: relaxdiego/package-pipeline@${PIPELINE_BUILD_ID}


workflows:
  #
  # Integration test for Docker jobs
  #
  integration-test-docker-jobs:
    jobs:
      - pipeline/render-build-info:
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

          versioning_scheme: semver2


      - pipeline/build-docker:
          requires:
            - pipeline/render-build-info
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

          dockerfile_path: src/tests/docker/Dockerfile
          docker_image_name: relaxdiego/package-pipeline-test
