#
# This template is a dynamic configuration that the main .circleci/config.yml
# renders and then triggers. For more information on dynamic configurations,
# see https://circleci.com/docs/2.0/dynamic-config/
#
# The purpose of this config is to allow our main workflow in .circleci/config.yml
# to test each of the jobs that we define in src/jobs. In effect, this is an
# integration test for the orb that this pipeline is building.
#
# Yeah, we're using a Circle CI config to test an orb which is essentially
# a packaged, parameterized Circle CI config. :-)
#
version: 2.1

orbs:
  pipeline: relaxdiego/package-pipeline@${PIPELINE_BUILD_ID}


workflows:
  # NOTE: We place all jobs under a single workflow so that we fan them into
  #       a single job that will wait for approval from a human to publish
  #       promote the orb to production.
  integration-tests:
    jobs:
      - pipeline/render-build-info:
          filters:
            tags:
              ignore:
                - .*

          versioning_scheme: semver2

      #
      # Integration test for Docker jobs
      #
      - pipeline/lint-docker:
          dockerfile_path: src/tests/docker/Dockerfile

      - pipeline/build-docker:
          requires:
            - pipeline/lint-docker
            - pipeline/render-build-info
          filters:
            tags:
              ignore:
                - .*

          dockerfile_path: src/tests/docker/Dockerfile
          docker_image_name: relaxdiego/package-pipeline-test

      #
      # Integration test for Circle CI Orb jobs
      #
      - pipeline/build-orb:
          requires:
            - pipeline/render-build-info
          filters:
            tags:
              ignore:
                - .*

          orb_src_path: src/tests/fixtures/orb
