#
# This template is a dynamic configuration that the main .circleci/config.yml
# renders and then triggers. For more information on dynamic configurations,
# see https://circleci.com/docs/2.0/dynamic-config/
#
# The purpose of this config is to allow our main workflow in .circleci/config.yml
# to test each of the jobs that we define in src/jobs. In effect, this is an
# integration test for the orb that this pipeline is building.
#
# Yeah, we're using a Circle CI config to test an orb which is essentially
# a packaged, parameterized Circle CI config. :-)
#
version: 2.1

orbs:
  pipeline: relaxdiego/package-pipeline@${PIPELINE_BUILD_ID}


workflows:
  integration-tests:
    jobs:
      #
      # NOTE: Don't use the "name" argument here so that the Circle CI UI
      #       will display the job's actual name allowing us to see at a
      #       glance which job failed integration tests.
      #

      #
      # Integration test for Docker jobs
      #

      - pipeline/render-build-info:
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

      - pipeline/docker-static-analysis:
          requires:
            - pipeline/render-build-info
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

          dockerfile: src/tests/docker/Dockerfile


      # - pipeline/docker-build:
      #     requires:
      #       - pipeline/docker-static-analysis
      #     filters:
      #       branches:
      #         only:
      #           - main
      #           - maint/.*
      #       tags:
      #         ignore:
      #           - .*
      #
      #     dockerfile: src/tests/docker/Dockerfile
      #     tag: relaxdiego/package-pipeline-test:0.1.0
