version: 2.1

orbs:
  pipeline: relaxdiego/package-pipeline@${PIPELINE_BUILD_ID}


workflows:
  vetting:
    jobs:

      #
      # Integration test for Docker jobs
      #

      - pipeline/render-build-info:
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

      - pipeline/docker-static-analysis:
          requires:
            - pipeline/render-build-info
          filters:
            branches:
              only:
                - main
                - maint/.*
            tags:
              ignore:
                - .*

          dockerfile: src/tests/docker/Dockerfile


      # - pipeline/docker-build:
      #     name: Build and test an orb
      #     requires:
      #       - pipeline/packer-static-analysis
      #     filters:
      #       branches:
      #         only:
      #           - main
      #           - maint/.*
      #       tags:
      #         ignore:
      #           - .*
      #
      #     dockerfile: tests/docker/Dockerfile
